// Subsets Font Awesome webfonts to the icons actually used by the site.
// Reads codepoints from node_modules/@fortawesome/fontawesome-free/css/all.min.css,
// runs pyftsubset (fonttools + brotli, see AGENTS.md) per family, and emits:
//   src/assets/fonts/fa-{solid,brands}-subset.woff2
//   src/assets/styles/fa-subset.css
// Run with: npm run subset:icons (re-run after adding/removing an icon).
// Keep the icon lists in sync with the fa-* classes used across src/.

import { execFileSync } from 'child_process'
import fs from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'

const rootDir = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const faCssPath = path.join(rootDir, 'node_modules/@fortawesome/fontawesome-free/css/all.min.css')
const webfontDir = path.join(rootDir, 'node_modules/@fortawesome/fontawesome-free/webfonts')
const outFontDir = path.join(rootDir, 'src/assets/fonts')
const outCssPath = path.join(rootDir, 'src/assets/styles/fa-subset.css')

const ICONS: Record<'solid' | 'brands', string[]> = {
  solid: [
    'star',
    'info-circle',
    'calendar-alt',
    'link',
    'arrow-right',
    'bookmark',
    'clock',
    'search',
    'times',
    'arrow-up',
    'envelope',
    'layer-group',
    'folder-open',
    'code',
    'scale-balanced',
    'tag',
    'book-open',
    'calendar-days',
  ],
  brands: ['github'],
}

const css = fs.readFileSync(faCssPath, 'utf-8')

// Returns the full codepoint INCLUDING the leading 'f' (e.g. 'f005' for fa-star).
// FA icon codepoints are 5 hex digits with a leading 'f'; dropping it (as 'U+005')
// silently produces a garbage font, so both the CSS rule and the pyftsubset
// --unicodes argument derive from this value.
const codepointFor = (name: string): string => {
  const re = new RegExp(`\\.fa-${name}:before[^{]*\\{content:"\\\\f([0-9a-f]{3})"`)
  const m = css.match(re)
  if (!m) throw new Error(`icon "fa-${name}" not found in all.min.css`)
  return `f${m[1]}`
}

const subset = (family: keyof typeof ICONS, codepoints: string[], outFile: string): void => {
  const source = path.join(webfontDir, family === 'solid' ? 'fa-solid-900.woff2' : 'fa-brands-400.woff2')
  const unicodeArg = codepoints.map((cp) => `U+${cp.toUpperCase()}`).join(',')
  execFileSync(
    'pyftsubset',
    [source, `--unicodes=${unicodeArg}`, '--flavor=woff2', `--output-file=${outFile}`],
    { stdio: 'inherit' },
  )
  verifyCmap(outFile, codepoints)
}

// Guards against silent font corruption: the produced woff2 must map every
// requested codepoint (asserted via fontTools' getBestCmap in Python).
const verifyCmap = (outFile: string, codepoints: string[]): void => {
  const py = [
    'from fontTools.ttLib import TTFont',
    'import sys',
    't = TTFont(sys.argv[1]).getBestCmap()',
    'want = set(int(x, 16) for x in sys.argv[2:])',
    'have = set(t) if t else set()',
    'missing = sorted(hex(c) for c in want - have)',
    'if missing:',
    '  raise SystemExit("cmap missing: " + ", ".join(missing))',
    'print("cmap ok:", ", ".join(hex(c) for c in sorted(have)))',
  ].join('\n')
  execFileSync('python', ['-c', py, outFile, ...codepoints], { stdio: 'inherit' })
}

const makeRules = (family: keyof typeof ICONS): string => {
  return ICONS[family]
    .map((name) => `.fa-${name}:before{content:"\\${codepointFor(name)}"}`)
    .join('')
}

const report: Record<string, { icons: string[]; size: number }> = {}
for (const [family, names] of Object.entries(ICONS)) {
  const codepoints = names.map((name) => codepointFor(name))
  const uniques = [...new Set(codepoints)]
  const outFile = path.join(outFontDir, `fa-${family}-subset.woff2`)
  subset(family as keyof typeof ICONS, uniques, outFile)
  report[family] = { icons: names, size: fs.statSync(outFile).size }
}

const baseCss = [
  '@font-face{font-family:"Font Awesome 6 Free";font-style:normal;font-weight:900;font-display:block;src:url("../fonts/fa-solid-subset.woff2") format("woff2")}',
  '@font-face{font-family:"Font Awesome 6 Brands";font-style:normal;font-weight:400;font-display:block;src:url("../fonts/fa-brands-subset.woff2") format("woff2")}',
  '.fa-solid,.fab,.far,.fas{-moz-osx-font-smoothing:grayscale;-webkit-font-smoothing:antialiased;display:inline-block;font-style:normal;font-variant:normal;line-height:1;text-rendering:auto}',
  '.fa-classic,.fa-regular,.fa-solid,.far,.fas{font-family:"Font Awesome 6 Free"}',
  '.fa-brands,.fab{font-family:"Font Awesome 6 Brands"}',
  '.fas{font-weight:900}',
  '.fab{font-weight:400}',
  '.fa-lg{font-size:1.25em;line-height:.05em;vertical-align:-.075em}',
  '.fa-fw{text-align:center;width:1.25em}',
  makeRules('solid'),
  makeRules('brands'),
].join('\n')

fs.mkdirSync(path.dirname(outCssPath), { recursive: true })
fs.writeFileSync(outCssPath, `/* Generated by scripts/subset-fa-icons.ts - do not edit manually */\n${baseCss}\n`)

console.log('fa-subset.css written:', outCssPath)
for (const [family, r] of Object.entries(report)) {
  console.log(`${family} (${r.icons.length} icons, ${r.size} bytes woff2): ${r.icons.join(', ')}`)
}
